[tools]
go = '1.24'
golangci-lint = '2.2.2'
node = '24.1.0'
"github:pulumi/pulumi" = '3.183.0'
yarn = '1.22.22'
dotnet = '8'
shellcheck = '0.10.0'
"npm:@anthropic-ai/claude-code" = '2.1.52'

[settings]
experimental = true
