provider: confluentcloud
lint: false
major-version: 1
providerDefaultBranch: main
env:
  CONFLUENT_CLOUD_API_KEY: ${{ secrets.CONFLUENT_CLOUD_API_KEY }}
  CONFLUENT_CLOUD_API_SECRET: ${{ secrets.CONFLUENT_CLOUD_API_SECRET }}
upstream-provider-repo: terraform-provider-confluent
makeTemplate: bridged
plugins:
  - name: random 
    version: "4.1.1"
team: ecosystem
