provider: docker
major-version: 3
aws: true
env:
  AWS_REGION: us-west-2
  ARM_CLIENT_ID: "30e520fa-12b4-4e21-b473-9426c5ac2e1e"
  ARM_SUBSCRIPTION_ID: "0282681f-7a9e-424b-80b2-96babd57a8a1"
  ARM_TENANT_ID: "706143bc-e1d4-4593-aee2-c9dc60ab9be7"
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  AZURE_LOCATION: westus
  PULUMI_GO_DEP_ROOT: /home/runner/work/pulumi-docker
