provider: gcp
gcp: true
major-version: 6
lint: false
parallel: 2
customLdFlag: "-X github.com/hashicorp/terraform-provider-google-beta/version.ProviderVersion={{.Tag}}"
env:
  GOOGLE_PROJECT: "pulumi-ci-gcp-provider"
  GOOGLE_REGION: "us-central1"
  GOOGLE_ZONE: "us-central1-a"

