provider: gcp
gcp: true
major-version: 6
lint: false
parallel: 2
providerVersion: "github.com/hashicorp/terraform-provider-google-beta/version.ProviderVersion"
env:
  GOOGLE_PROJECT: "pulumi-ci-gcp-provider"
  GOOGLE_REGION: "us-central1"
  GOOGLE_ZONE: "us-central1-a"
  PULUMI_MISSING_DOCS_ERROR: true
upstream-provider-org: pulumi
upstream-provider-repo: terraform-provider-google-beta
makeTemplate: bridged
plugins:
  - name: random
    version: "4.8.2"
  - name: kubernetes
    version: "3.20.0"
  - name: tls
    version: "4.6.0"
