provider: newrelic
major-version: 5
env:
  NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
  NEW_RELIC_ACCOUNT_ID: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
upstream-provider-org: pulumi
makeTemplate: bridged
team: ecosystem
extra-ld-flags: true
