provider: artifactory
major-version: 5
env:
  ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}
  ARTIFACTORY_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN}}
  PULUMI_MISSING_DOCS_ERROR: true
upstream-provider-major-version: /v7
providerDefaultBranch: main
makeTemplate: bridged
plugins:
  - name: random 
    version: "4.3.1"
  - name: time
    version: "0.0.15"
team: ecosystem
