provider: http
major-version: 0
lint: false
providerDefaultBranch: main
makeTemplate: bridged
publishRegistry: false
env:
  HTTP_TOKEN: ${{ secrets.HTTP_TOKEN }}
team: ecosystem
javaGenVersion: "v0.9.7"
