provider: sumologic
major-version: 1
env:
  SUMOLOGIC_ACCESSID: ${{ secrets.SUMOLOGIC_ACCESSID }}
  SUMOLOGIC_ACCESSKEY: ${{ secrets.SUMOLOGIC_ACCESSKEY }}
  SUMOLOGIC_ENVIRONMENT: ${{ secrets.SUMOLOGIC_ENVIRONMENT }}
makeTemplate: bridged
plugins:
  - name: aws 
    version: "4.0.0"
  - name: gcp 
    version: "5.0.0"
team: ecosystem
