name: Test Windows
on:
  pull_request:

jobs:
  test:
    name: Test Mise On Windows
    runs-on: windows-latest
    steps:
      - name: Install mise
        uses: jdx/mise-action@d16887ba50704baed7de72bd1e82e04391e4457a # v3
        with:
          # Latest working version. See https://github.com/jdx/mise/discussions/6781
          version: 2025.10.16
          github_token: ${{ secrets.GITHUB_TOKEN }}

